/*
"Usuarios": [
    {
      "UsuarioId": 1,
      "AplicacaoId": 1,
      "Nome": "Administrador do Suite Omega",
      "Apelido": "Master SO",
      "Login": "master",
      "Senha": "admin123",
      "SituacaoCadastralId": 2,
      "PerguntaSecreta": "Master",
      "RespostaSecreta": "Master",
      "FlagStatus": true,
      "FlagBloqueioPorIp": true,
      "QuantidadeOcorrenciaDeErroDaSenha": 0,
      "FlagSenhaExpirada": false,
      "FlagAlterarSenhaNoProximoAcesso": false,
      "FlagUsuarioDeSistema": true,
      "DataHoraSenhaExpirada": null,
      "CadastroDataHora": "2018-11-29 00:00",
      "CadastroUsuarioId": 1,
      "AtualizacaoDataHora": null,
      "AtualizacaoUsuarioId": null,
      "DataUltimoAcesso": "2018-11 29 00:00",
      "NSU": "E14EE7B5-63FE-4B12-8084-0860A84DDA9D",
      "FlagTrace": false,
      "URLSite": "http://www.suiteomega.com.br",
      "URLRetorno": null,
      "URLEscuta": null,
      "TipoDeEntidadeId": null,
      "SaldoTotal": 0,
      "FlagAceitaTermos": true,
      "FlagAceitaNewsletter": false,
      "FlagAceitaProgramasAfiliados": false,
      "PessoaId": null
    },
    {
      "UsuarioId": 2,
      "AplicacaoId": 1,
      "Nome": "Daniela Puccini",
      "Apelido": "Puccini",
      "Login": "dpuccini",
      "Senha": "senha123",
      "SituacaoCadastralId": 2,
      "PerguntaSecreta": true,
      "RespostaSecreta": true,
      "FlagStatus": true,
      "FlagBloqueioPorIp": false,
      "QuantidadeOcorrenciaDeErroDaSenha": 0,
      "FlagSenhaExpirada": false,
      "FlagAlterarSenhaNoProximoAcesso": false,
      "FlagUsuarioDeSistema": false,
      "DataHoraSenhaExpirada": null,
      "CadastroDataHora": "2018-11-29 00:00",
      "CadastroUsuarioId": 1,
      "AtualizacaoDataHora": null,
      "AtualizacaoUsuarioId": null,
      "DataUltimoAcesso": "2018-11 29 00:00",
      "NSU": "4CFE75FA-6C9F-4013-BBC0-2973A66739AD",
      "FlagTrace": null,
      "URLSite": null,
      "URLRetorno": null,
      "URLEscuta": null,
      "TipoDeEntidadeId": null,
      "SaldoTotal": 0,
      "FlagAceitaTermos": true,
      "FlagAceitaNewsletter": true,
      "FlagAceitaProgramasAfiliados": false,
      "PessoaId": null
    },
    {
      "UsuarioId": 3,
      "AplicacaoId": 1,
      "Nome": "Silmara Forcellini de Freitas",
      "Apelido": "Silmara",
      "Login": "sforcellini",
      "Senha": "senha123",
      "SituacaoCadastralId": 2,
      "PerguntaSecreta": "Silmara",
      "RespostaSecreta": "Silmara",
      "FlagStatus": true,
      "FlagBloqueioPorIp": false,
      "QuantidadeOcorrenciaDeErroDaSenha": 0,
      "FlagSenhaExpirada": false,
      "FlagAlterarSenhaNoProximoAcesso": false,
      "FlagUsuarioDeSistema": false,
      "DataHoraSenhaExpirada": null,
      "CadastroDataHora": "2018-11-29 00:00",
      "CadastroUsuarioId": 1,
      "AtualizacaoDataHora": null,
      "AtualizacaoUsuarioId": null,
      "DataUltimoAcesso": "2018-11 29 00:00",
      "NSU": "D28879A1-C4E1-49B6-8F2E-D398051CE849",
      "FlagTrace": false,
      "URLSite": null,
      "URLRetorno": null,
      "URLEscuta": null,
      "TipoDeEntidadeId": null,
      "SaldoTotal": 0,
      "FlagAceitaTermos": true,
      "FlagAceitaNewsletter": true,
      "FlagAceitaProgramasAfiliados": false,
      "PessoaId": null
    },
    {
      "UsuarioId": 4,
      "AplicacaoId": 1,
      "Nome": "Bruna Martins da Silva",
      "Apelido": "Bruna",
      "Login": "brumartins",
      "Senha": "senha123",
      "SituacaoCadastralId": 2,
      "PerguntaSecreta": "Bruna",
      "RespostaSecreta": "Bruna",
      "FlagStatus": true,
      "FlagBloqueioPorIp": false,
      "QuantidadeOcorrenciaDeErroDaSenha": 0,
      "FlagSenhaExpirada": false,
      "FlagAlterarSenhaNoProximoAcesso": false,
      "FlagUsuarioDeSistema": false,
      "DataHoraSenhaExpirada": null,
      "CadastroDataHora": "2018-11-29 00:00",
      "CadastroUsuarioId": 1,
      "AtualizacaoDataHora": null,
      "AtualizacaoUsuarioId": null,
      "DataUltimoAcesso": "2018-11 29 00:00",
      "NSU": "DB15D8E6-5AE6-4581-9F30-E45073AFB837",
      "FlagTrace": false,
      "URLSite": null,
      "URLRetorno": null,
      "URLEscuta": null,
      "TipoDeEntidadeId": null,
      "SaldoTotal": 0,
      "FlagAceitaTermos": true,
      "FlagAceitaNewsletter": true,
      "FlagAceitaProgramasAfiliados": false,
      "PessoaId": null
    },
    {
      "UsuarioId": 5,
      "AplicacaoId": 1,
      "Nome": "Danila Maria de Moura",
      "Apelido": "Danila",
      "Login": "dmmoura",
      "Senha": "senha123",
      "SituacaoCadastralId": 2,
      "PerguntaSecreta": "Danila",
      "RespostaSecreta": "Danila",
      "FlagStatus": true,
      "FlagBloqueioPorIp": false,
      "QuantidadeOcorrenciaDeErroDaSenha": 0,
      "FlagSenhaExpirada": false,
      "FlagAlterarSenhaNoProximoAcesso": false,
      "FlagUsuarioDeSistema": false,
      "DataHoraSenhaExpirada": null,
      "CadastroDataHora": "2018-11-29 00:00",
      "CadastroUsuarioId": 1,
      "AtualizacaoDataHora": null,
      "AtualizacaoUsuarioId": null,
      "DataUltimoAcesso": "2018-11 29 00:00",
      "NSU": "377A9585-E474-498D-9551-B108EBBA4044",
      "FlagTrace": false,
      "URLSite": null,
      "URLRetorno": null,
      "URLEscuta": null,
      "TipoDeEntidadeId": null,
      "SaldoTotal": 0,
      "FlagAceitaTermos": true,
      "FlagAceitaNewsletter": true,
      "FlagAceitaProgramasAfiliados": false,
      "PessoaId": null
    },
    {
      "UsuarioId": 6,
      "AplicacaoId": 1,
      "Nome": "Dante Benvenuto",
      "Apelido": "Dante",
      "Login": "dbenvenuto",
      "Senha": "senha123",
      "SituacaoCadastralId": 2,
      "PerguntaSecreta": "Dante",
      "RespostaSecreta": "Dante",
      "FlagStatus": true,
      "FlagBloqueioPorIp": false,
      "QuantidadeOcorrenciaDeErroDaSenha": 0,
      "FlagSenhaExpirada": false,
      "FlagAlterarSenhaNoProximoAcesso": false,
      "FlagUsuarioDeSistema": false,
      "DataHoraSenhaExpirada": null,
      "CadastroDataHora": "2018-11-29 00:00",
      "CadastroUsuarioId": 1,
      "AtualizacaoDataHora": null,
      "AtualizacaoUsuarioId": null,
      "DataUltimoAcesso": "2018-11 29 00:00",
      "NSU": "87196BC3-81F4-4283-A23F-6E2C0A8924A7",
      "FlagTrace": false,
      "URLSite": null,
      "URLRetorno": null,
      "URLEscuta": null,
      "TipoDeEntidadeId": null,
      "SaldoTotal": 0,
      "FlagAceitaTermos": true,
      "FlagAceitaNewsletter": true,
      "FlagAceitaProgramasAfiliados": false,
      "PessoaId": null
    }*/